version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: Inferdata@123
      MYSQL_DATABASE: microdosing_system
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./microdosing-system-backend
    ports:
      - "5000:5000"
    volumes:
      - ./microdosing-system-backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./microdosing-system-frontend
    ports:
      - "5173:80"   # 👈 Exposes frontend at localhost:5173
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
