"""empty message

Revision ID: ac771df8a371
Revises: 7acde050b394
Create Date: 2025-05-26 14:33:06.201186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac771df8a371'
down_revision = '7acde050b394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smtp_profiles')
    op.drop_table('logo')
    op.drop_table('report_configs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_configs',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sender', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('recipient', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('include_kpis', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('include_charts', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('include_table', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('logo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('smtp_profiles',
    sa.Column('smtp_profile_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sender', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('smtp_profile_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
